# 03 02 Exercícios Pandas

---

In [16]:
import pandas as pd
import re
import numpy as np

## EX01

* Carregue para um DataFrame a lista de municípios de fronteira do Brasil utilizando o arquivo "https://github.com/fernandosola/analisedados-python/raw/master/dados/arq_municipios_fronteiricos.tsv".

In [19]:
# Complete o código abaixo para realizar a leitura do arquivo
# o arquivo utiliza tabulação como separador
# dentro de strings a tabulação é representada como \t
df = pd.read_csv(
    "dados/arq_municipios_fronteiricos.tsv",
    sep='\t',
    encoding='utf8',
)


# Visualize as 5 primeiras linhas do DataFrame
df.head()

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000
0,1 - Aceguá,Rio Grande do Sul,1.550,4.138,"2,66",71.638.000,17.266,ni
1,2 - Acrelândia,Acre,1.575,11.520,"7,31",114.350.000,9.986,"0,680"
2,3 - Alecrim,Rio Grande do Sul,315.000,7.357,"23,35",44.373.000,5.944,"0,743"
3,4 - Almeirim,Pará,72.960,30.903,"0,42",462.258.000,13.485,"0,745"
4,5 - Alta Floresta d'Oeste,Rondônia,7.067,23.857,"3,37",186.812.000,6.525,"0,715"

* Realize um tratamento na coluna Município para remover os números e hífens.
    * primeiro crie uma que função recebe uma string com o nome do município, realiza a remoção dos números e hifens e retorna a nova string tratada
    * faça os testes com a sua função até que o resultado esteja satisfatório
    * passe a sua função como parâmetro para o método apply do DataFrame

In [20]:
# função que irá realizar o tratamento para um município
def tratar_nome_municipio(nome_municipio):
    nome_municipio_tratado = re.sub(r'([\d]* [–-] )(.*)', r'\2', nome_municipio)
    return nome_municipio_tratado

# faça um teste de sua função para verificar se a transformação está correta

'Aceguá'

In [21]:
# aplique a função utilizando o método apply

In [22]:
# exiba todos os dados e verifique se o resultado está correto

0                   Aceguá
1               Acrelândia
2                  Alecrim
3                 Almeirim
4    Alta Floresta d'Oeste
Name: Município, dtype: object

In [23]:
# com todos os municípios devidamente tratados
# sobrescreva a coluna Município com os novos valores


# exiba as informações

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000
0,Aceguá,Rio Grande do Sul,1.550,4.138,"2,66",71.638.000,17.266,ni
1,Acrelândia,Acre,1.575,11.520,"7,31",114.350.000,9.986,"0,680"
2,Alecrim,Rio Grande do Sul,315.000,7.357,"23,35",44.373.000,5.944,"0,743"
3,Almeirim,Pará,72.960,30.903,"0,42",462.258.000,13.485,"0,745"
4,Alta Floresta d'Oeste,Rondônia,7.067,23.857,"3,37",186.812.000,6.525,"0,715"

## EX02

Ainda utilizando o DataFrame carregado no exercício anterior, verifique os tipos de dados das colunas do dataframe. Todos os dados numéricos deverão ser transformados para tipos numéricos.

* utilize o método info() do DataFrame para saber detalhes dos tipos de dados das colunas
* verifique se os números possuem os símbolos de decimal e separadores de milhar compatíveis com a linguagem. Se necessário, fazer as substituições pertinentes.

In [26]:
# verifique os tipos das colunas do DataFrame: df_muni_front

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 8 columns):
Município                          122 non-null object
Estado                             122 non-null object
Área territorial                   122 non-null float64
População (IBGE/2007)              122 non-null float64
Densidade demográfica (hab/km2)    122 non-null object
PIB (IBGE/2005)                    122 non-null object
PIB per capita (R$)                122 non-null object
IDH/2000                           122 non-null object
dtypes: float64(2), object(6)
memory usage: 7.7+ KB

In [27]:
# faça a conversão do campo 'Área territorial'
def converter_para_float(texto):
    try:
        if type(texto) == str:
            t = texto.replace(' ', '')
            t = t.replace('.', '')
            t = t.replace(',', '.')
            n = float(t)
            return n
        elif type(texto) == int or type(texto) == float:
            return texto
    except:
        pass
    return np.NaN

# faça os testes com a sua função

186812000.0

In [28]:
# substitua a coluna pelos valores convertidos

# faça o mesmo para todas as colunas numéricas

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000
0,Aceguá,Rio Grande do Sul,1.550,4.138,2.66,71638000.0,17266.0,NaN
1,Acrelândia,Acre,1.575,11.520,7.31,114350000.0,9986.0,0.680
2,Alecrim,Rio Grande do Sul,315.000,7.357,23.35,44373000.0,5944.0,0.743
3,Almeirim,Pará,72.960,30.903,0.42,462258000.0,13485.0,0.745
4,Alta Floresta d'Oeste,Rondônia,7.067,23.857,3.37,186812000.0,6525.0,0.715

In [29]:
# imprima novamente as informações das colunas e verifique os tipos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 8 columns):
Município                          122 non-null object
Estado                             122 non-null object
Área territorial                   122 non-null float64
População (IBGE/2007)              122 non-null float64
Densidade demográfica (hab/km2)    122 non-null float64
PIB (IBGE/2005)                    122 non-null float64
PIB per capita (R$)                122 non-null float64
IDH/2000                           104 non-null float64
dtypes: float64(6), object(2)
memory usage: 7.7+ KB

In [30]:
# imprima novamente as primeiras linhas do DataFrame

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000
0,Aceguá,Rio Grande do Sul,1.550,4.138,2.66,71638000.0,17266.0,NaN
1,Acrelândia,Acre,1.575,11.520,7.31,114350000.0,9986.0,0.680
2,Alecrim,Rio Grande do Sul,315.000,7.357,23.35,44373000.0,5944.0,0.743
3,Almeirim,Pará,72.960,30.903,0.42,462258000.0,13485.0,0.745
4,Alta Floresta d'Oeste,Rondônia,7.067,23.857,3.37,186812000.0,6525.0,0.715

## EX03

Crie uma coluna com a sigla dos estados.

* crie um set à partir da coluna Estados. Atribua a uma variável chamada __nomes_estados__.

In [32]:
# crie o set e verifique o seu conteúdo
nomes_estados = set(df['Estado'])
nomes_estados

{'Acre',
 'Amapá',
 'Amazonas',
 'Mato Grosso',
 'Mato Grosso do Sul',
 'Paraná',
 'Pará',
 'Rio Grande do Sul',
 'Rondônia',
 'Roraima',
 'Santa Cataria',
 'Santa Catarina'}

Você identificou um problema no nome dos estados?
Vamos corrigir no final.

* crie um dicionário onde o nome completo do estado é a chave e a sigla é o valor: __dic_nomes_siglas__

In [33]:
# crie o dicionário
dic_nomes_siglas = {'Acre': 'AC',
 'Amapá': 'AP',
 'Amazonas': 'AM',
 'Mato Grosso': 'MT',
 'Mato Grosso do Sul': 'MS',
 'Paraná': 'PR',
 'Pará': 'PA',
 'Rio Grande do Sul': 'RS',
 'Rondônia': 'RO',
 'Roraima': 'RR',
 'Santa Cataria': 'SC',
 'Santa Catarina': 'SC',
}

* utilize a função map do DataFrame para criar uma nova coluna de siglas à partir dos nomes dos estados. Passe o dicionário criado para a função map. Atribua a Série criada à variável __coluna_siglas_uf__.

In [35]:
# faça o mapeamento dos valores e atribua a : coluna_siglas_uf


# verifique os 10 primeiros itens criados

0    RS
1    AC
2    RS
3    PA
4    RO
5    RR
6    RO
7    RR
8    MS
9    MS
Name: Estado, dtype: object

In [36]:
# crie a coluna sigla


# verifique as informações do dataframe

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000,sigla
0,Aceguá,Rio Grande do Sul,1.550,4.138,2.66,71638000.0,17266.0,NaN,RS
1,Acrelândia,Acre,1.575,11.520,7.31,114350000.0,9986.0,0.680,AC
2,Alecrim,Rio Grande do Sul,315.000,7.357,23.35,44373000.0,5944.0,0.743,RS
3,Almeirim,Pará,72.960,30.903,0.42,462258000.0,13485.0,0.745,PA
4,Alta Floresta d'Oeste,Rondônia,7.067,23.857,3.37,186812000.0,6525.0,0.715,RO

In [37]:
# verifique quantos registros possuem o nome do estado de Santa Catarina escrito errado

(1, 9)

In [39]:
# faça a correção dos registros que possuem o nome do estado de Santa Catarina escrito errado

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000,sigla
13,Bandeirante,Santa Catarina,146.0,3.028,20.73,21423000.0,7546.0,0.765,SC
18,Belmonte,Santa Catarina,94.0,2.681,28.52,21670000.0,9954.0,0.759,SC
38,Dionísio Cerqueira,Santa Catarina,378.0,14.792,39.13,91757000.0,6293.0,0.747,SC
50,Guaraciaba,Santa Catarina,331.0,10.604,32.03,103642000.0,10111.0,NaN,SC
54,Itapiranga,Santa Catarina,280.0,15.238,54.42,298682000.0,22447.0,0.832,SC

In [ ]:
# verifique, novamente, quantos registros possuem o nome do estado de Santa Catarina escrito errado

## EX04

Identifique quais municípios possuem 2 ou mais desvios na coluna PIB.

In [40]:
# normalize a coluna PIB em quantidade de desvios padrão

0   -0.258100
1   -0.183876
2   -0.305481
3    0.420717
4   -0.057952
Name: PIB (IBGE/2005), dtype: float64

In [41]:
# quais cidades possuem mais de 2 desvios

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000,sigla
33,Corumbá,Mato Grosso do Sul,65.304,114.279,1.74,1.557253e+09,13234.0,0.771,MS
45,Foz do Iguaçu,Paraná,618.000,311.336,503.70,4.853331e+09,16102.0,0.802,PR
89,Porto Velho,Rondônia,34.082,369.345,10.83,3.656512e+09,9779.0,0.763,RO

## EX05

Perguntas rápidas.

In [43]:
# quantos registros possuem NaN na coluna IDH/2000?

18

In [44]:
# quantas cidades por estado?

Rio Grande do Sul     29
Paraná                17
Acre                  17
Mato Grosso do Sul    12
Santa Catarina        10
Roraima                9
Amazonas               9
Rondônia               9
Mato Grosso            5
Pará                   3
Amapá                  2
Name: Estado, dtype: int64

In [50]:
# faça a ordenação do DataFrame pelo nome do município
# a ordenação está correta?

from libs.texto import TratamentoTexto

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005),PIB per capita (R$),IDH/2000,sigla
52,Iracema,Roraima,14.119,5.863,0.41,4.673500e+07,7712.0,0.713,RR
53,Itaipulandia,Paraná,336.000,8.581,25.53,8.315800e+07,9782.0,0.760,PR
54,Itapiranga,Santa Catarina,280.000,15.238,54.42,2.986820e+08,22447.0,0.832,SC
55,Itaqui,Rio Grande do Sul,3.404,36.361,10.68,4.870620e+08,11494.0,0.801,RS
56,Jaguarao,Rio Grande do Sul,2.054,27.944,13.60,1.930180e+08,6116.0,0.764,RS
57,Japora,Mato Grosso do Sul,420.000,7.362,17.52,2.397600e+07,3350.0,0.636,MS
58,Japura,Amazonas,55.791,5.281,0.09,2.710000e+07,2080.0,NaN,AM
59,Jordao,Acre,5.429,6.059,1.11,2.380500e+07,5138.0,0.475,AC
60,Laranjal do Jari,Amapá,30.966,37.491,1.21,1.829010e+08,5099.0,NaN,AP
61,Mancio Lima,Acre,4.672,13.785,2.95,4.970500e+07,3899.0,0.642,AC
62,Manoel Urbano,Acre,9.387,7.148,0.76,3.126800e+07,4095.0,0.601,AC
63,Marechal Rondon,Paraná,748.000,44.562,59.57,6.328180e+08,14155.0,0.829,PR
64,Marechal Thaumaturgo,Acre,7.744,13.061,1.68,3.764500e+07,4452.0,0.533,AC
65,Mercedes,Paraná,201.000,4.713,23.44,5.448000e+07,11210.0,0.816,PR
66,Mundo Novo,Mato Grosso do Sul,479.000,15.968,33.33,9.824700e+07,6884.0,0.761,MS
67,Normandia,Roraima,6.967,7.118,1.02,5.107100e+07,9573.0,0.600,RR
69,Nova Mamore,Rondônia,10.072,21.162,2.10,1.245380e+08,6388.0,NaN,RO
68,Novo Machado,Rio Grande do Sul,219.000,4.246,19.38,2.521000e+07,5922.0,0.773,RS
70,Obidos,Pará,28.021,46.793,1.66,1.384890e+08,2820.0,0.681,PA
71,Oiapoque,Amapá,22.625,19.181,0.84,1.432440e+08,8828.0,NaN,AP
72,Oriximina,Pará,107.603,55.175,0.51,7.768450e+08,14620.0,0.717,PA
73,Pacaraima,Roraima,8.028,8.640,0.10,6.060800e+07,7378.0,0.718,RR
74,Paraiso,Santa Catarina,179.000,4.195,23.43,3.360500e+07,8312.0,0.773,SC
75,Paranhos,Mato Grosso do Sul,1.302,11.092,8.51,4.370300e+07,4094.0,0.676,MS
76,Pato Bragado,Paraná,135.000,4.631,34.30,4.169700e+07,9542.0,0.821,PR
77,Pedras Altas,Rio Grande do Sul,1.377,2.546,1.84,2.782900e+07,10135.0,NaN,RS
78,Perola d'Oeste,Paraná,206.000,7.046,34.20,4.578100e+07,6961.0,0.759,PR
79,Pimenteiras do Oeste,Rondônia,6.015,2.358,0.39,3.716300e+07,14201.0,0.715,RO
80,Pirapo,Rio Grande do Sul,292.000,2.988,10.23,1.796000e+07,5879.0,0.720,RS
81,Placido de Castro,Acre,2.047,17.258,8.43,1.398140e+08,8377.0,0.683,AC
...,...,...,...,...,...,...,...,...,...
92,Porto Xavier,Rio Grande do Sul,281.000,10.857,38.63,7.133700e+07,6285.0,0.762,RS
93,Pranchita,Paraná,226.000,5.811,25.71,5.733100e+07,10120.0,0.803,PR
94,Princesa,Santa Catarina,86.000,2.604,30.27,1.880300e+07,7709.0,NaN,SC
95,Quarai,Rio Grande do Sul,3.148,22.552,7.16,1.624120e+08,6444.0,0.776,RS
96,Rodrigues Alves,Acre,3.305,12.428,3.76,5.146800e+07,5254.0,0.550,AC
97,Roque Gonzales,Rio Grande do Sul,347.000,7.297,21.02,5.465500e+07,7626.0,0.749,RS
98,Santa Helena,Paraná,758.000,22.794,30.07,2.199730e+08,10226.0,0.799,PR
99,Santa Helena,Santa Catarina,81.000,2.437,30.08,1.654490e+08,14812.0,0.787,SC
100,Santa Isabel do Rio Negro,Amazonas,62.846,16.921,0.26,2.423100e+07,3181.0,NaN,AM
101,Santa Rosa do Purus,Acre,5.981,3.948,0.66,1.532100e+07,4513.0,0.525,AC
102,Santa Vitoria do Palmar,Rio Grande do Sul,5.244,31.183,5.94,2.892230e+08,8360.0,0.799,RS
103,Santana do Livramento,Rio Grande do Sul,6.950,83.479,12.01,5.983870e+08,6138.0,0.803,RS
104,Santo Antonio do Ica,Amazonas,12.308,29.249,2.37,6.827500e+07,1958.0,NaN,AM
105,Santo Antonio do Sudoeste,Paraná,326.000,18.565,56.94,9.252100e+07,5101.0,0.715,PR
106,Sao Borja,Rio Grande do Sul,3.616,65.671,17.10,5.968040e+08,8862.0,0.798,RS
107,Sao Francisco do Guapore,Rondônia,4.747,15.710,3.30,1.081830e+08,6453.0,NaN,RO
108,Sao Gabriel da Cachoeira,Amazonas,109.185,39.129,0.35,1.110930e+08,3261.0,0.567,AM
109,Sao Jose do Cedro,Santa Catarina,280.000,13.699,48.92,1.537220e+08,11838.0,0.804,SC
110,Sao Miguel do Iguacu,Paraná,851.000,25.341,29.77,2.973000e+08,11065.0,0.779,PR
111,Sao Nicolau,Rio Grande do Sul,485.000,5.909,12.18,3.233800e+07,5290.0,0.713,RS
112,Sena Madureira,Acre,25.278,34.230,1.35,2.343810e+08,7105.0,0.652,AC
113,Serranopolis do Iguacu,Paraná,484.000,4.327,8.94,5.287600e+07,10635.0,0.796,PR
114,Sete Quedas,Mato Grosso do Sul,826.000,10.659,12.90,5.410300e+07,6445.0,0.719,MS
115,Tabatinga,Amazonas,3.225,45.293,14.04,1.167550e+08,2655.0,NaN,AM
116,Tiradentes do Sul,Rio Grande do Sul,234.000,6.928,29.60,4.292600e+07,6577.0,0.746,RS
117,Tunapolis,Santa Catarina,133.000,4.650,34.96,4.084500e+07,9420.0,0.821,SC
118,Uiramuta,Roraima,8.066,7.403,0.91,2.725100e+07,4238.0,0.542,RR
119,Uruguaiana,Rio Grande do Sul,5.716,123.743,21.64,1.187038e+09,8798.0,0.788,RS
120,Vila Bela da Santissima Trindade,Mato Grosso,13.631,13.886,1.01,1.169080e+08,8047.0,0.715,MT
121,Xapuri,Acre,5.251,14.314,2.72,8.237700e+07,6016.0,0.669,AC

___
__Material produzido para o curso__:
* Introdução à Análise de Dados com Python

__Autor__:
* Fernando Sola Pereira

__Revisão__:
* 1.1